version: 0.2

phases:
  install:
    commands:
      - echo "Updating packages..."
      - sudo apt-get update -y
      - echo "Installing Nginx..."
      - sudo apt-get install nginx -y

  build:
    commands:
      - echo "Copying index.html to Nginx web root..."
      - sudo cp index.html /var/www/html/

  post_build:
    commands:
      - echo "Deployment Completed Successfully!"
artifacts:
  files:
    - /var/www/html/index.html

